### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [Velkor2017/Capstone#4]
Great job with this project so far, I can tell that you worked really hard on this project. It looks like you've come a long way since you've started. You did great with applying your own style and flair to this project and it shows. There were a couple of key improvements that you can make with one of the sections for applying some media queries. I would suggest try to look at examples from others on how to tackle. You should be able to use `display: none` to hide certain elements in mobile size in combination with media queries. Otherwise, great work here.

Grade: Satisfactory

**Comment by Velkor2017** [comment]
Thank you for your kind compliments, much appreciated!! I'll make a note of your advice and develop this website a bit further, thanks again....
